language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_script: composer install

script: composer test

notifications:
  - email: false
